teams:
  - name: ipram-maintainers
    maintainers:
      - evanp8io
    members: 
      - gkp8io
  - name: lf-staff
    maintainers:
      - ryjones
    members:
      - jwagantall
      - thelinuxfoundation
repositories:
  - name: .github
    teams:
      ipram-maintainers: maintain
      lf-staff: maintain
    visibility: public
  - name: impl
    teams:
      ipram-maintainers: maintain
      lf-staff: maintain
    visibility: public
  - name: docs
    teams:
      ipram-maintainers: maintain
      lf-staff: maintain
    visibility: public
  - name: governance
    teams:
      ipram-maintainers: maintain
      lf-staff: maintain
    visibility: public
  - name: spec
    teams:
      ipram-maintainers: maintain
      lf-staff: maintain
    visibility: public
  - name: TSC
    teams:
      ipram-maintainers: maintain
      lf-staff: maintain
    visibility: public
